name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login --username pedro826 --password Miche+3lles

      - name: Build and push Docker image
        run: |
          docker build -t pedro826/api_weather .
          docker push pedro826/api_weather
