name: Deploy to Azure Container Instance

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Azure CLI and jq
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          apt-get install jq | sudo bash

      - name: Extract Azure credentials
        run: |
          # Extraire le contenu du secret Azure Credentials et le stocker dans une variable
          AZURE_CREDENTIALS=$(echo -e "${{ secrets.AZURE_CREDENTIALS }}")
          
          # Extraire les valeurs des clés à l'aide de grep, cut et awk
          client_id=$(echo "${{ secrets.AZURE_CREDENTIALS }}" | grep -o 'clientId: [^,]*' | cut -d ' ' -f 2)
          client_secret=$(echo "${{ secrets.AZURE_CREDENTIALS }}" | grep -o 'clientSecret: [^,]*' | cut -d ' ' -f 2)
          tenant_id=$(echo "${{ secrets.AZURE_CREDENTIALS }}" | grep -o 'tenantId: [^,]*' | cut -d ' ' -f 2)
          
          # Afficher les valeurs des clés
          echo "Client ID: $client_id"
          echo "Client Secret: $client_secret"
          echo "Tenant ID: $tenant_id"

      - name: Login on Azure
        run: |    
          az login --service-principal -u "$client_id" -p "$client_secret" --tenant "$tenant_id"
      - name: Connect to Azure Container Registry
        run: |
          az acr login --name $(echo -e "${{ secrets.REGISTRY_LOGIN_SERVER }}")

      - name: Build image
        run: |
          docker build -t $(echo -e "${{ secrets.REGISTRY_LOGIN_SERVER }}").azurecr.io/20230418 .
      - name: Docker login
        run: |    
          docker login $(echo -e "${{ secrets.REGISTRY_LOGIN_SERVER }}").azurecr.io -u $(echo -e "${{ secrets.REGISTRY_USERNAME}}") -p $(echo -e "${{ secrets.REGISTRY_PASSWORD}}")
      - name: Docker push
        run: |
          docker push $(echo -e "${{ secrets.REGISTRY_LOGIN_SERVER }}").azurecr.io/20230418

      - name: Deploy to Azure Container Instance
        run: |
          az container create --resource-group $(echo -e "${{ secrets.RESOURCE_GROUP }}") --name 20230418 --image $(echo -e "${{ secrets.REGISTRY_LOGIN_SERVER }}")azurecr.io/20230418 --cpu 1 --memory 2 --ports 8080






