name: Deploy to Azure Container Instance

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Azure CLI and jq
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          apt-get install jq | sudo bash

      - name: Extract Azure credentials
        run: |
          # Extraire le contenu du secret Azure Credentials et le stocker dans une variable
          AZURE_CREDENTIALS=$(echo -e "${{ secrets.AZURE_CREDENTIALS }}")
          
          echo "$AZURE_CREDENTIALS" | awk -F ', *' '/clientId/ {print $2}'
          echo "$AZURE_CREDENTIALS" | awk -F ', *' '/clientSecret/ {print $2}'
          echo "$AZURE_CREDENTIALS" | awk -F ', *' '/subscriptionId/ {print $2}'
          echo "$AZURE_CREDENTIALS" | awk -F ', *' '/tenantId/ {print $2}'

