name: Deploy to Azure Container Instance

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Azure CLI and jq
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          apt-get install jq | sudo bash

      - name: Extract Azure credentials
        run: |
          # Extraire le contenu du secret Azure Credentials et le stocker dans une variable
          AZURE_CREDENTIALS=$(echo -e "${{ secrets.AZURE_CREDENTIALS }}")
          
          # Extraire les valeurs des clés à l'aide de grep, cut et awk
          client_id=$(echo "${{ secrets.AZURE_CREDENTIALS }}" | grep -o 'clientId: [^,]*' | cut -d ' ' -f 2)
          client_secret=$(echo "${{ secrets.AZURE_CREDENTIALS }}" | grep -o 'clientSecret: [^,]*' | cut -d ' ' -f 2)
          subscription_id=$(echo "${{ secrets.AZURE_CREDENTIALS }}" | grep -o 'subscriptionId: [^,]*' | cut -d ' ' -f 2)
          tenant_id=$(echo "${{ secrets.AZURE_CREDENTIALS }}" | grep -o 'tenantId: [^,]*' | cut -d ' ' -f 2)
          
          # Afficher les valeurs des clés
          echo "Client ID: $client_id"
          echo "Client Secret: $client_secret"
          echo "Subscription ID: $subscription_id"
          echo "Tenant ID: $tenant_id"




